/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AgeGateInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "doAdultThing"
      | "requiredYear"
      | "verified"
      | "verifier"
      | "verify"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AgeVerified"): EventFragment;

  encodeFunctionData(
    functionFragment: "doAdultThing",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requiredYear",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [
      [BigNumberish, BigNumberish],
      [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      [BigNumberish, BigNumberish]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "doAdultThing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredYear",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verified", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace AgeVerifiedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgeGate extends BaseContract {
  connect(runner?: ContractRunner | null): AgeGate;
  waitForDeployment(): Promise<this>;

  interface: AgeGateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  doAdultThing: TypedContractMethod<[], [string], "view">;

  requiredYear: TypedContractMethod<[], [bigint], "view">;

  verified: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  verifier: TypedContractMethod<[], [string], "view">;

  verify: TypedContractMethod<
    [
      pA: [BigNumberish, BigNumberish],
      pB: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      pC: [BigNumberish, BigNumberish]
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "doAdultThing"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requiredYear"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verified"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [
      pA: [BigNumberish, BigNumberish],
      pB: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]],
      pC: [BigNumberish, BigNumberish]
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgeVerified"
  ): TypedContractEvent<
    AgeVerifiedEvent.InputTuple,
    AgeVerifiedEvent.OutputTuple,
    AgeVerifiedEvent.OutputObject
  >;

  filters: {
    "AgeVerified(address)": TypedContractEvent<
      AgeVerifiedEvent.InputTuple,
      AgeVerifiedEvent.OutputTuple,
      AgeVerifiedEvent.OutputObject
    >;
    AgeVerified: TypedContractEvent<
      AgeVerifiedEvent.InputTuple,
      AgeVerifiedEvent.OutputTuple,
      AgeVerifiedEvent.OutputObject
    >;
  };
}
