/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AgeGate__factory } from "./AgeGate__factory";
export { IVerifier__factory } from "./IVerifier__factory";
